export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            width: "428px",
            height: "926px",
            backgroundColor: "#121212",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        ></div>
   
      {children}
      
      </body>
    </html>
  );
}
